name: JBake Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.BLOG_TOKEN }}
      - name: Install SDKMAN!
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
      - name: Set SDKMAN! environment variables
        run: echo "SDKMAN_DIR=$HOME/.sdkman" >> $GITHUB_ENV
      - name: Install JBake
        run: sdk install jbake
      - name: Check JBake version
        run: jbake -v
      - name: Build
        run: jbake -b -s
      - name: Commit and Push
        run: |
          git config --local user.email "gantoin@pm.me"
          git config --local user.name "gantoin"
          git add .
          git commit -m "🤖 [Automated] JBake Build"
          git push
