name: JBake Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JBake
        run: |
          brew install jbake
      - name: Build
        run: |
          jbake -b
      - name: Commit and Push
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "your_username"
          git add .
          git commit -m "🤖 [Automated] JBake Build"
          git push
