name: JBake Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.BLOG_TOKEN }}
      - name: Build
        run: docker run --rm -u jbake -v "$PWD":/mnt/site jbake/jbake:latest bake
      - name: Commit and Push
        run: |
          git config --local user.email "gantoin@pm.me"
          git config --local user.name "gantoin"
          git add .
          git commit -m "🤖 [Automated] JBake Build"
          git push
