name: JBake Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.BLOG_TOKEN }}
      - name: Install JBake
        run: |
          apt-get update
          apt-get install -y unzip
          wget https://github.com/jbake-org/jbake/releases/download/v2.6.7/jbake-2.6.7-bin.zip
          unzip jbake-2.6.7-bin.zip
          export PATH=$PATH:$PWD/jbake-2.6.7/bin
      - name: Build
        run: jbake -b -s
      - name: Commit and Push
        run: |
          git config --local user.email "gantoin@pm.me"
          git config --local user.name "gantoin"
          git add .
          git commit -m "🤖 [Automated] JBake Build"
          git push
